package Interfaz;
import Mundo.Notas;
import javax.swing.JOptionPane;
/**
 * @author Alejandro Erazo
 */

public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        
        //-- Codigo para mostrar la tabla en el centro de la pantalla --//
        this.setLocationRelativeTo(null);
    }
    
    // ----------------------------------
    // Metodos
    // ----------------------------------
    
    public void Limpiar ( )
    {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(490, 410));
        setMinimumSize(new java.awt.Dimension(490, 410));
        setPreferredSize(new java.awt.Dimension(490, 410));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        jLabel1.setText("Notas USC");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(203, 11, 116, 29);

        jLabel2.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel2.setText("Nota 1:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 101, 58, 22);

        jLabel3.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel3.setText("Nota 3:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 193, 58, 22);

        jLabel4.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel4.setText("Nota 2:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 147, 58, 22);

        jLabel5.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel5.setText("%");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 190, 20, 22);

        jLabel7.setFont(new java.awt.Font("Brooke Smith Script", 1, 18)); // NOI18N
        jLabel7.setText("By: A.E");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(410, 0, 74, 24);

        jLabel8.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel8.setText("Porcentaje");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(167, 58, 80, 22);

        jLabel9.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel9.setText("Nota 3:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(290, 170, 58, 22);

        jLabel10.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel10.setText("%");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(220, 100, 20, 22);

        jLabel11.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel11.setText("%");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(220, 150, 20, 22);

        jLabel12.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel12.setText("Nota Final:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(290, 90, 89, 22);

        jButton1.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 330, 97, 31);

        jButton2.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 278, 95, 31);

        jButton3.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jButton3.setText("Calcular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 236, 97, 31);

        jTextField1.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(86, 98, 55, 28);

        jTextField2.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(86, 144, 55, 28);

        jTextField3.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(86, 190, 55, 28);

        jTextField4.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jTextField4.setEnabled(false);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(290, 200, 80, 28);

        jTextField5.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jTextField5.setEnabled(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(290, 120, 80, 28);

        jComboBox1.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "30", "40", "50", "60", "70", "80", "90" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(167, 98, 51, 28);

        jComboBox2.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "30", "40", "50", "60", "70", "80", "90" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(167, 144, 51, 28);

        jComboBox3.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "30", "40", "50", "60", "70", "80", "90" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(167, 190, 51, 28);

        jLabel6.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-10, -10, 510, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //-- Cierra el programa --//
        System.exit(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        //-- BOTON LIMPIAR --//
        Limpiar();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //-- BOTON CALCULAR --//
        
        //-- Crea el objeto MundoPlop para usar sus metodos --//
        Notas nota = new Notas();

        //-- Se ejecuta el metodo --//
        double Porcentaje1 = Integer.parseInt(jComboBox1.getSelectedItem().toString());
        double Porcentaje2 = Integer.parseInt(jComboBox2.getSelectedItem().toString());
        double Porcentaje3 = Integer.parseInt(jComboBox3.getSelectedItem().toString());
        
        double P1 = nota.dividir(Porcentaje1);
        double P2 = nota.dividir(Porcentaje2);
        double P3 = nota.dividir(Porcentaje3);
            
        if (jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor llenar los campos");
        }
        else if (jTextField3.getText().isEmpty()){
            if (Porcentaje1 + Porcentaje2 + Porcentaje3 < 100){
                JOptionPane.showMessageDialog(null, "El % debe dar 100%");
            }
            else if (Porcentaje1 + Porcentaje2 + Porcentaje3 > 100){
                JOptionPane.showMessageDialog(null, "El % no puede superar el 100%");
            }
            else{
                //-- Extrae los datos registrados en los campos --//
                double Nota1 = Double.parseDouble(jTextField1.getText());
                double Nota2 = Double.parseDouble(jTextField2.getText());
                
                double res = nota.AveriguarNota(Nota1, Nota2, P1, P2, P3);
                this.jTextField4.setText(String.valueOf(res));
            }
        }
        else {
            if (Porcentaje1 + Porcentaje2 + Porcentaje3 < 100){
                JOptionPane.showMessageDialog(null, "El % debe dar 100%");
            }
            else if (Porcentaje1 + Porcentaje2 + Porcentaje3 > 100){
                JOptionPane.showMessageDialog(null, "El % no puede superar el 100%");
            }
            else{
                //-- Extrae los datos registrados en los campos --//
                double Nota1 = Double.parseDouble(jTextField1.getText());
                double Nota2 = Double.parseDouble(jTextField2.getText());
                double Nota3 = Double.parseDouble(jTextField3.getText());

                //-- Se ejecuta el metodo --//
                double resultado = nota.NotaFinal(Nota1, Nota2, Nota3, P1, P2, P3);
                this.jTextField5.setText(String.valueOf(resultado));
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
